#!/usr/bin/env php
<?php


if ($argc != 3) {
  printf("Usage: %s wp-dir host\n", $argv[0]);
  die;
}

$wp_path = $argv[1];
$host_name = $argv[2];
$wp_dir = basename($wp_path);

if (!is_dir($wp_path)) {
  printf("Invalid dir\n");
  die;
}

require $wp_path."/wp-config.php";

if (DB_PASSWORD == "") {
    $popt = "";
} else {
    $popt = "-p" . DB_PASSWORD;
}
if (!preg_match('/^http:\/\//', $host_name)) {
    $host_name = "http://$host_name";    
}
echo "Changing siteurl to $host_name...\n";
$sql = "UPDATE wp_options SET option_value = '$host_name' WHERE option_name = 'siteurl'";
system(sprintf("mysql -h %s -u %s $popt %s -e \"%s\"", DB_HOST, DB_USER, DB_NAME, $sql));
echo "Changing siteurl to $host_name...\n";
$sql = "UPDATE wp_options SET option_value = '$host_name' WHERE option_name = 'siteurl'";
system(sprintf("mysql -h %s -u %s $popt %s -e \"%s\"", DB_HOST, DB_USER, DB_NAME, $sql));
